addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang-format-3.8

language: c

compiler:
  - clang
  - gcc

branches:
  only:
    - master

script:
  - mkdir build
  - cd build
  - cmake ..
  - make reformat
  - |
    if [[ -n $(git diff) ]]; then
      echo "You must run 'make reformat' before submitting a pull request"
      echo ""
      git diff
      exit -1
    fi
  - make
